<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Approved Training Providers_tab</name>
   <tag></tag>
   <elementGuidId>ed073ed2-2149-4bbc-9003-9b3377592a22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-tab/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c0b52b2-16a9-4825-af6d-50a5ab8350b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4e1add61-051a-4bbf-be24-f7023bae3c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-homepage[1]/app-tabs[1]/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tab-content&quot;]/app-tab[1]/div[@class=&quot;tab&quot;]</value>
      <webElementGuid>61efc7ef-d023-4ce9-94d3-e4decb1e6ad4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-tab/div</value>
      <webElementGuid>bab0d4e1-2e49-4c2c-b5cb-0b0e8a052436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-tab/div</value>
      <webElementGuid>08465978-8739-4066-ab9e-5f46c8f6c96f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
