<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From date_ontario-input start-date ng_5374fa</name>
   <tag></tag>
   <elementGuidId>6031f106-ac41-4167-8222-007f147c54a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ontario-input.start-date.ng-pristine.ng-valid.ng-touched</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb454d21-2fba-45a6-9eef-565981c3f5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>6756a207-a664-4bf6-94a2-6705d0476646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-input start-date ng-pristine ng-valid ng-touched</value>
      <webElementGuid>cabd6f10-d3f7-423c-967b-df12c61836c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2022-07-11</value>
      <webElementGuid>1cc79f08-2813-4ac8-bfa2-f0c2f23a76e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>Tue Oct 11 2022 00:00:00 GMT-0400 (Eastern Daylight Time)</value>
      <webElementGuid>5480e3b3-32ca-4cee-9661-830d79c37160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-homepage[1]/app-tabs[1]/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tab-content&quot;]/app-marketplace[1]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column form-input-div ontario-small-12 ontario-medium-6 ontario-large-4&quot;]/app-date-range[1]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-large-6 ontario-columns&quot;]/input[@class=&quot;ontario-input start-date ng-pristine ng-valid ng-touched&quot;]</value>
      <webElementGuid>b2330afe-989c-4c73-a791-3b65738de920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='date']</value>
      <webElementGuid>2a8f1cfa-7d5a-4f7e-8738-c7a37e97ac62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-marketplace/div/div[6]/app-date-range/div/div/input</value>
      <webElementGuid>00a2c096-c6db-4291-8cc8-cd83a90ffa53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date-range/div/div/input</value>
      <webElementGuid>eca3298d-9140-406a-9470-488f77a5320d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date']</value>
      <webElementGuid>c012da42-0fd6-491b-bd99-5a7042e56164</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
